apiVersion: v1
kind: ConfigMap
metadata:
  name: food-master-config
data:
  APP_VERSION: dev
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_CSRF_TRUSTED_ORIGINS: ""
  DJANGO_DEBUG: "False"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  FOOD_DELIVER_DB_HOST: food-master-db
  FOOD_DELIVER_DB_NAME: the_food_mas2
  FOOD_DELIVER_DB_PORT: "3306"
  FOOD_DELIVER_DB_USER: root
  IMPORT_SQL_ON_START: "true"
  SERVICE_DB_HOST: food-master-db
  SERVICE_DB_PORT: "3306"
  SERVICE_DB_USER: root
  USER_DB_NAME: user_db
  TRADE_DB_NAME: trade_db
  LIFESTYLE_DB_NAME: life_db
