# Generated by Django 5.2.14 on 2026-06-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_blog_id_alter_comment_id_alter_food_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
