# Generated by Django 5.2.14 on 2026-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(default=0),
        ),
    ]
