# Generated by Django 5.2.14 on 2026-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_order_rider_play_playorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '骑手'), (2, '商家'), (3, '管理员')], default=0),
        ),
    ]
