# Generated by Django 3.2.11 on 2026-08-29 06:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("content", models.TextField()),
                ("author_id", models.BigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "blogs",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("addr", models.CharField(max_length=100)),
                ("price_clock", models.FloatField(blank=True, null=True)),
                ("price_day", models.FloatField(blank=True, null=True)),
                ("price_double_clock", models.FloatField(blank=True, null=True)),
                ("price_double_day", models.FloatField(blank=True, null=True)),
                ("price_special", models.FloatField(blank=True, null=True)),
                ("image", models.CharField(blank=True, default="", max_length=200)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("inf", models.CharField(blank=True, default="", max_length=200)),
                ("orders", models.IntegerField(default=0)),
                ("ratenum", models.IntegerField(default=0)),
                ("merchant_id", models.BigIntegerField(db_index=True)),
            ],
            options={
                "db_table": "hotels",
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("addr", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("start_time", models.CharField(default="09:00", max_length=50)),
                ("open_time", models.CharField(default="24h", max_length=50)),
                ("image", models.CharField(blank=True, default="", max_length=200)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("ratenum", models.IntegerField(default=0)),
                ("inf", models.CharField(blank=True, default="", max_length=200)),
                ("orders", models.IntegerField(default=0)),
                ("merchant_id", models.BigIntegerField(db_index=True)),
            ],
            options={
                "db_table": "plays",
            },
        ),
        migrations.CreateModel(
            name="PlayOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("num", models.PositiveIntegerField()),
                ("visit_time", models.DateTimeField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("cost", models.FloatField(default=0.0)),
                ("comment", models.CharField(blank=True, default="", max_length=200)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("pos", models.IntegerField(default=4)),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="lifestyle_service_lifestyle.play",
                    ),
                ),
            ],
            options={
                "db_table": "play_orders",
            },
        ),
        migrations.CreateModel(
            name="HotelOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("room_type", models.CharField(max_length=20)),
                ("duration", models.PositiveIntegerField()),
                ("checkin_time", models.DateTimeField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("cost", models.FloatField(default=0.0)),
                ("comment", models.CharField(blank=True, default="", max_length=200)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("pos", models.IntegerField(default=4)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="lifestyle_service_lifestyle.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_orders",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="lifestyle_service_lifestyle.blog",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
    ]
