# Generated by Django 3.2.11 on 2026-08-29 06:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("price", models.FloatField()),
                ("image", models.CharField(blank=True, default="", max_length=200)),
                ("sale", models.IntegerField(default=0)),
                ("saleperson", models.IntegerField(default=0)),
                ("providor", models.CharField(max_length=40)),
                ("ratenum", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("inf", models.CharField(blank=True, default="", max_length=200)),
                ("merchant_id", models.BigIntegerField(db_index=True)),
                ("is_off_shelf", models.BooleanField(default=False)),
                ("is_sold_out", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "foods",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                (
                    "rider_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("num", models.PositiveIntegerField()),
                ("cost", models.FloatField(default=0.0)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("address", models.CharField(default="", max_length=100)),
                ("comment", models.CharField(blank=True, default="", max_length=200)),
                ("pos", models.IntegerField(default=0)),
                ("is_abnormal", models.BooleanField(default=False)),
                (
                    "scoretofood",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "scoretodeliver",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trade_service_trade.food",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="GroupBuyCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("num", models.PositiveIntegerField()),
                ("cost", models.FloatField(default=0.0)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("status", models.IntegerField(default=0)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="trade_service_trade.food",
                    ),
                ),
            ],
            options={
                "db_table": "group_buy_coupons",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("num", models.PositiveIntegerField()),
                ("cost", models.FloatField(default=0.0)),
                ("address", models.CharField(default="", max_length=100)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="trade_service_trade.food",
                    ),
                ),
            ],
            options={
                "db_table": "cart_items",
            },
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("user_id", "food"), name="unique_user_food_cart_item"
            ),
        ),
    ]
