# Generated by Django 3.2.11 on 2026-06-01 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20260601_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='inf',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
