# Generated by Django 3.2.11

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('checkin_time', models.DateTimeField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cost', models.FloatField(default=0.0)),
                ('comment', models.CharField(default='', max_length=200)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('pos', models.IntegerField(default=4)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
