# Generated by Django 3.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_hotelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='myapp.user'),
        ),
    ]
