# Generated by Django 3.2.11 on 2026-06-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20260601_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='saleperson',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
