# Generated by Django 5.2.14 on 2026-06-05 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=100)),
                ('price_clock', models.FloatField(blank=True, null=True)),
                ('price_day', models.FloatField(blank=True, null=True)),
                ('price_double_clock', models.FloatField(blank=True, null=True)),
                ('price_double_day', models.FloatField(blank=True, null=True)),
                ('price_special', models.FloatField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('inf', models.CharField(default='', max_length=200)),
                ('orders', models.IntegerField(default=0)),
                ('ratenum', models.IntegerField(default=0)),
            ],
        ),
    ]
