# Generated by Django 5.2.14 on 2026-06-08 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_food_hotel_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_orders', to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('start_time', models.CharField(default='09:00', max_length=50)),
                ('open_time', models.CharField(default='24h', max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('ratenum', models.IntegerField(default=0)),
                ('inf', models.CharField(default='', max_length=200)),
                ('orders', models.IntegerField(default=0)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('visit_time', models.DateTimeField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cost', models.FloatField(default=0.0)),
                ('comment', models.CharField(default='', max_length=200)),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('pos', models.IntegerField(default=4)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.play')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
