"""Public HTTP contracts used by API coverage tests and test reports."""

PUBLIC_API_CONTRACTS = {
    "user-service": (
        ("GET", "/health/live"),
        ("GET", "/health/ready"),
        ("GET", "/health/version"),
        ("POST", "/register"),
        ("POST", "/login"),
        ("POST", "/logout"),
        ("GET", "/users/<int:user_id>"),
        ("PATCH", "/users/<int:user_id>/profile"),
        ("PATCH", "/users/<int:user_id>/status"),
        ("PATCH", "/users/<int:user_id>/role"),
        ("GET", "/internal/users"),
    ),
    "trade-service": (
        ("GET", "/health/live"),
        ("GET", "/health/ready"),
        ("GET", "/health/version"),
        ("GET", "/foods"),
        ("POST", "/foods"),
        ("GET", "/foods/<int:food_id>"),
        ("PATCH", "/foods/<int:food_id>/status"),
        ("POST", "/orders"),
        ("GET", "/orders/<int:order_id>"),
        ("POST", "/orders/<int:order_id>/comment"),
        ("POST", "/orders/<int:order_id>/accept"),
        ("POST", "/orders/<int:order_id>/prepare"),
        ("POST", "/orders/<int:order_id>/pickup"),
        ("POST", "/orders/<int:order_id>/deliver"),
        ("GET", "/cart"),
        ("POST", "/cart"),
        ("PATCH", "/cart/<int:item_id>"),
        ("DELETE", "/cart/<int:item_id>"),
        ("POST", "/cart/checkout"),
        ("POST", "/groupbuy"),
        ("POST", "/groupbuy/redeem"),
        ("GET", "/rider/orders"),
    ),
    "lifestyle-service": (
        ("GET", "/health/live"),
        ("GET", "/health/ready"),
        ("GET", "/health/version"),
        ("GET", "/hotels"),
        ("POST", "/hotels"),
        ("GET", "/hotels/<int:hotel_id>"),
        ("POST", "/hotel-orders"),
        ("GET", "/hotel-orders/<int:order_id>"),
        ("POST", "/hotel-orders/<int:order_id>/comment"),
        ("GET", "/plays"),
        ("POST", "/plays"),
        ("GET", "/plays/<int:play_id>"),
        ("POST", "/play-orders"),
        ("GET", "/play-orders/<int:order_id>"),
        ("POST", "/play-orders/<int:order_id>/comment"),
        ("GET", "/blogs"),
        ("POST", "/blogs"),
        ("GET", "/blogs/<int:blog_id>"),
        ("DELETE", "/blogs/<int:blog_id>"),
        ("POST", "/blogs/<int:blog_id>/comments"),
        ("DELETE", "/comments/<int:comment_id>"),
    ),
}


def route_patterns(urlpatterns):
    """Return normalized route patterns from a Django URL configuration."""
    return {f"/{pattern.pattern}" for pattern in urlpatterns}
