apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: food-master
resources:
  - namespace.yaml
  - configmap.yaml
  - database.yaml
  - web.yaml
  - nginx.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: food-master
      app.kubernetes.io/managed-by: kustomize
